sudo: true
dist: trusty
cache: false
env:
  global:
    - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    - coreId=04tf4000001I1CsAAK
    - logicId=04tf4000001I1CxAAK
    - uiId=04tf4000001I1D2AAK
    - securityId=04tf4000001I1D7AAK
before_install:
# delete the following line before encrypting your server.key
- openssl aes-256-cbc -K $encrypted_8c437a15935b_key -iv $encrypted_8c437a15935b_iv
-in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
# Authroize Dev Hub
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
# Push all source to scratch org and run tests
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human -w 30
- sfdx force:org:delete -u ciorg -p
# Push packages to scratch org
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a pkgInstallOrg
- sfdx force:package:install -w 30 -u pkgInstallOrg -i $coreId
- sfdx force:package:install -w 30 -u pkgInstallOrg -i $logicId
- sfdx force:package:install -w 30 -u pkgInstallOrg -i $uiId
- sfdx force:package:install -w 30 -u pkgInstallOrg -i $securityId
- sfdx force:org:delete -u pkgInstallOrg -p
